language: node_js
node_js:
    - node
    - 10
    - 8
cache: npm
install:
    - npm install
    - npm install -g codecov
script:
    - npm run test
    - codecov
branches:
    except:
        - '/^v\d+\.\d+\.\d+$/'
jobs:
    include:
        - stage: deploy
          if: branch == master && !fork
          node_js: 'node' # pre-installed version
          script:
              - npm install -g semantic-release@^15
              - semantic-release
